dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: q5lObGCmDXlCZBklnTv8xghv6GN7ukBpDmE234PNPZ2bEtwJFoPf+Ap7yathE9+ABfb+aV9IWvbmG0kj6ChAbgbyxvFYPtNQxaSReo0+32zweFJGGj/DvpGtTuC3Bo3VKruw0eidoFiRvi5QnsCK3dvn9bMgZ1TWVbP9gHNBDRjb4sq0aT7laDJmnyubcZABKGd4jGPxD0JH3ZO9qfqCni/sFr1yLB3z3XdXiP0RKv5YYkOosIslMc79TzHggKq3CQtnspOvzM+4yes+lz3/LbBi2n7oEoveZYQJINSYn0TGlYvBxY+BlmDztSdeP4A1nopun2AxmgyKLFyjtpmAYuCG6KEbbnKLi/2tOiQ9hdkXRV+utjgRrFfQGAyWGLRmm9qMDdbXV0LFFYA0Xv+XqLEjKD7b0DeaJT1Pffwt5VGSjGq2hwKBseCpF5YwJBHOGiw654e0GI9XlGpiH/yDyRajntARmhLVoreodqzA87POb+0WidToNRZDmyrMYG+bGIw+carpwa8jqRnng7ql+zm6KJOyQu1FbrmqPOBwnoAyLYBEeNCudLVHOiHJBQXiKZKT+hMOBYp7x+Ef4TRxT69FAqkc1voOH78bBpFnqjJfd3LEszYLtgxBFWFF4ffBsUH5CczJoENe9ihLssTiDyX1GOVyo8e9/PLgF25q4YM=
