version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus:${VER_COMMENT}
    networks:
      backend-net:
        aliases:
          - prometheus
      frontend-net:
        aliases:
          - prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      backend-net:
        aliases:
          - node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      backend-net:
        aliases:
          - cadvisor
volumes:
  prometheus_data:

networks:
  frontend-net:
    ipam:
      config:
        - subnet: 10.1.1.0/24
  backend-net:
    ipam:
      config:
        - subnet: 10.1.2.0/24
