version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - esnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - esdata:/usr/share/elasticsearch/data

    expose:
      - 9200
    ports:
      - "9200:9200"
    
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - esnet

volumes:
  esdata:

networks:
  esnet: