version: '3.3'
services:
  post_db:
    image: mongo:${VER_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      backend-net:
        aliases:
          - ${DB_POST}
          - ${DB_COMMENT}
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      - frontend-net
    environment:
      - POST_SERVICE_HOST=${MS_POST_NAME}
      - COMMENT_SERVICE_HOST=${MS_COMMENT_NAME}
  post:
    image: ${USERNAME}/post:${VER_POST}
    networks:
      backend-net:
        aliases:
          - ${MS_POST_NAME}
      frontend-net:
        aliases:
          - ${MS_POST_NAME}
    environment:
      - POST_DATABASE_HOST=${DB_POST}
  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      backend-net:
        aliases:
          - ${MS_COMMENT_NAME}
      frontend-net:
        aliases:
          - ${MS_COMMENT_NAME}
    environment:
      - COMMENT_DATABASE_HOST=${DB_COMMENT}
  prometheus:
    image: ${USERNAME}/prometheus:${VER_COMMENT}
    networks:
      backend-net:
        aliases:
          - prometheus
      frontend-net:
        aliases:
          - prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    networks:
      backend-net:
        aliases:
          - node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  post_db:
  prometheus_data:

networks:
  frontend-net:
    ipam:
      config:
        - subnet: 10.1.1.0/24
  backend-net:
    ipam:
      config:
        - subnet: 10.1.2.0/24
